const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY),$=id=>document.getElementById(id);let links=[],badges=[];
function msg(id,text,ok=true){$(id).textContent=text;$(id).className=ok?"msg":"msg error"}
async function init(){if(!window.SUPABASE_URL.startsWith("http"))return msg("loginMsg","Add your Supabase values to config.js.",false);const{data:{session}}=await sb.auth.getSession();if(session)dashboard()}
async function dashboard(){$("login").hidden=true;$("dash").hidden=false;const[{data:p},{data:l},{data:b},{data:s}]=await Promise.all([sb.from("profiles").select("*").eq("id",1).maybeSingle(),sb.from("links").select("*").eq("profile_id",1).order("sort_order"),sb.from("badges").select("*").eq("profile_id",1).order("sort_order"),sb.from("site_stats").select("views").eq("id",1).maybeSingle()]);if(p){["name","username","bio","avatar_url","background_url","accent","accent2","song_title","song_artist","music_url"].forEach(k=>$(k).value=p[k]??"");$("show_status").checked=p.show_status!==false;$("music_enabled").checked=!!p.music_enabled}links=l||[];badges=(b||[]).map(x=>x.label);renderLinks();renderBadges();$("views").textContent=Number(s?.views||0).toLocaleString()}
function esc(s){return String(s).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;")}
function renderLinks(){$("linksEditor").innerHTML="";links.forEach((x,i)=>{const d=document.createElement("div");d.className="editor";d.innerHTML=`<input value="${esc(x.icon||"↗")}" placeholder="icon"><input value="${esc(x.name||"")}" placeholder="Name"><input value="${esc(x.url||"")}" placeholder="https://..."><button type="button" class="remove">×</button>`;d.querySelector(".remove").onclick=()=>{links.splice(i,1);renderLinks()};$("linksEditor").appendChild(d)})}
function renderBadges(){$("badgesEditor").innerHTML="";badges.forEach((x,i)=>{const d=document.createElement("div");d.className="editor";d.style.gridTemplateColumns="1fr 36px";d.innerHTML=`<input value="${esc(x)}"><button type="button" class="remove">×</button>`;d.querySelector("input").oninput=e=>badges[i]=e.target.value;d.querySelector(".remove").onclick=()=>{badges.splice(i,1);renderBadges()};$("badgesEditor").appendChild(d)})}
$("loginForm").onsubmit=async e=>{e.preventDefault();const{error}=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error)return msg("loginMsg",error.message,false);dashboard()};
$("logout").onclick=async()=>{await sb.auth.signOut();location.reload()};
$("profileForm").onsubmit=async e=>{e.preventDefault();const row={id:1,name:$("name").value,username:$("username").value,bio:$("bio").value,avatar_url:$("avatar_url").value,background_url:$("background_url").value,accent:$("accent").value,accent2:$("accent2").value,show_status:$("show_status").checked};const{error}=await sb.from("profiles").upsert(row);msg("profileMsg",error?.message||"Profile saved.",!error)};
$("musicForm").onsubmit=async e=>{e.preventDefault();const row={id:1,song_title:$("song_title").value,song_artist:$("song_artist").value,music_url:$("music_url").value,music_enabled:$("music_enabled").checked};const{error}=await sb.from("profiles").upsert(row);msg("musicMsg",error?.message||"Music saved.",!error)};
$("addLink").onclick=()=>{links.push({icon:"↗",name:"New link",url:"https://"});renderLinks()};
$("saveLinks").onclick=async()=>{links=[...document.querySelectorAll("#linksEditor .editor")].map(d=>({profile_id:1,icon:d.children[0].value,name:d.children[1].value,url:d.children[2].value})).filter(x=>x.name&&x.url);let{error}=await sb.from("links").delete().eq("profile_id",1);if(error)return msg("linksMsg",error.message,false);({error}=links.length?await sb.from("links").insert(links.map((x,i)=>({...x,sort_order:i}))):{error:null});msg("linksMsg",error?.message||"Links saved.",!error)};
$("addBadge").onclick=()=>{badges.push("✦ new badge");renderBadges()};
$("saveBadges").onclick=async()=>{let{error}=await sb.from("badges").delete().eq("profile_id",1);if(error)return msg("badgesMsg",error.message,false);const rows=badges.filter(Boolean).map((label,i)=>({profile_id:1,label,sort_order:i}));({error}=rows.length?await sb.from("badges").insert(rows):{error:null});msg("badgesMsg",error?.message||"Badges saved.",!error)};
init();
