create table if not exists public.profiles(
 id bigint primary key default 1,
 name text not null default 'yourname',
 username text not null default '@yourname',
 bio text not null default 'welcome to my little corner of the internet ♡',
 avatar_url text default '',
 background_url text default '',
 accent text not null default '#ea55ad',
 accent2 text not null default '#9a5ce8',
 show_status boolean not null default true,
 song_title text default '',
 song_artist text default '',
 music_url text default '',
 music_enabled boolean not null default false
);
create table if not exists public.links(
 id bigint generated by default as identity primary key,
 profile_id bigint not null references public.profiles(id) on delete cascade,
 icon text default '↗',
 name text not null,
 url text not null,
 sort_order integer not null default 0
);
create table if not exists public.badges(
 id bigint generated by default as identity primary key,
 profile_id bigint not null references public.profiles(id) on delete cascade,
 label text not null,
 sort_order integer not null default 0
);
create table if not exists public.site_stats(id bigint primary key default 1,views bigint not null default 0);
insert into public.profiles(id) values(1) on conflict(id) do nothing;
insert into public.site_stats(id) values(1) on conflict(id) do nothing;
alter table public.profiles enable row level security;
alter table public.links enable row level security;
alter table public.badges enable row level security;
alter table public.site_stats enable row level security;
drop policy if exists "public read profiles" on public.profiles; create policy "public read profiles" on public.profiles for select using(true);
drop policy if exists "public read links" on public.links; create policy "public read links" on public.links for select using(true);
drop policy if exists "public read badges" on public.badges; create policy "public read badges" on public.badges for select using(true);
drop policy if exists "public read stats" on public.site_stats; create policy "public read stats" on public.site_stats for select using(true);
drop policy if exists "auth edit profiles" on public.profiles; create policy "auth edit profiles" on public.profiles for all to authenticated using(true) with check(true);
drop policy if exists "auth edit links" on public.links; create policy "auth edit links" on public.links for all to authenticated using(true) with check(true);
drop policy if exists "auth edit badges" on public.badges; create policy "auth edit badges" on public.badges for all to authenticated using(true) with check(true);
create or replace function public.increment_views() returns void language sql security definer set search_path=public as $$ update public.site_stats set views=views+1 where id=1; $$;
grant execute on function public.increment_views() to anon,authenticated;
